apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

configMapGenerator:
- name: pipeline-install-config
  env: params.env
  behavior: merge

secretGenerator:
- name: mysql-secret
  env: mysql-secret.env
  behavior: merge

bases:
- ../../base/installs/multi-user
- ../../base/metadata/base
- ../../base/metadata/options/istio
- ../../third-party/argo/installs/cluster
- minio-azure-gateway
- ../../third-party/metacontroller/base



# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines
namespace: kubeflow